### ISSUE TITLE
no other cell output when timing is used

### ISSUE THREAD

**Issue by nicohofdtz** [deshaw/jupyterlab-execute-time#5] opened 2020-05-06 13:51 UTC
Hey,

when enabling timing, the output from the plugin is the only cell output I get.
Is this an inteded behaviour?

Best regards
Nico

**Comment by corralm** [comment] 2020-05-06 23:40
I'm experiencing the same issue as well. I'm on Jupyter Lab 2.1.2 and I've enabled the 'record timing' in settings.
![Screen Shot 2020-05-06 at 4 39 04 PM](https://user-images.githubusercontent.com/47012573/81238962-4b66bc80-8fb8-11ea-8a0d-47ae9e1b9de4.png)
![Screen Shot 2020-05-06 at 4 37 53 PM](https://user-images.githubusercontent.com/47012573/81238965-4bff5300-8fb8-11ea-8f68-ffcb96789632.png)
![Screen Shot 2020-05-06 at 4 37 31 PM](https://user-images.githubusercontent.com/47012573/81238966-4d308000-8fb8-11ea-8ac4-c1fac9380356.png)

**Comment by sidazhou** [comment] 2020-05-08 07:15
Same issue here. I think I have jupyter lab 2.0.2

**Comment by sidazhou** [comment] 2020-05-09 03:15
I uninstalled the extension, and there is still no output when I set `{"recordTiming": true}`
So, this might be a bug in jupyter labs? And not a bug of this extension?

**Comment by mlucool** [comment] 2020-05-13 12:38
Hi,

The best way to ensure that cells are recording time is to look at the metadata for each cell. Can you confirm you see something like this (click on the wrench icon on the left side bar):

![image](https://user-images.githubusercontent.com/1813603/81812984-e4379380-94f4-11ea-9106-91237adc7969.png)


> I uninstalled the extension, and there is still no output when I set {"recordTiming": true}
So, this might be a bug in jupyter labs? And not a bug of this extension?

This sounds like a jupyterlab bug if you have the same issue without the extension. If so, please raise it there.

**Comment by corralm** [comment] 2020-05-13 18:47
I created a new environment with the same version of Jupyter Lab (2.1.2) and the extension works. I'm not sure what root cause of the issue was...

P.S. This is an extremely useful extension, thanks!

**Comment by mlucool** [comment] 2020-05-13 19:51
@nicohofdtz is this good to close?

**Comment by sidazhou** [comment] 2020-05-15 06:40
Upgraded pip or conda or jupyter or something, and the problem is gone. Extension version was unchanged, using `jupyterlab-execute-time-1.0.0.tgz`. I would conclude it's not extension's issue.

**Comment by mlucool** [comment] 2020-05-20 20:44
Closing, but please reopen if there is still an issue.

**Closed by mlucool** 2020-05-20 20:44 UTC
