### ISSUE TITLE
JupyterLab settings missing

### ISSUE THREAD

**Issue by psychemedia** [deshaw/jupyterlab-execute-time#119] opened 2024-05-13 17:13 UTC
In JL v4.1.8 I'm not seeing any settings for this [`jupyterlab-execute-time`](https://github.com/deshaw/jupyterlab-execute-time) extension?

**Comment by krassowski** [comment] 2024-05-13 18:39
If you close the settings and open them again, does it show up?

**Comment by krassowski** [comment] 2024-05-13 20:04
If so then this is a duplicate of https://github.com/deshaw/jupyterlab-execute-time/issues/98 - there is an upstream bug that settings for plugins which load later than others do not show up if the settings panel is open on startup (https://github.com/jupyterlab/jupyterlab/issues/15871). It is quite annoying because it also affects the settings built-in plugins like Inline Completer.

**Comment by psychemedia** [comment] 2024-05-14 15:54
Nope... opening and closing the settings editor had no effect. I guessed at the path name for the user settings file too to see if I could manually override some settings but either I guessed the path wrong, or that didn't work either...

**Comment by krassowski** [comment] 2024-05-16 12:33
> opening and closing the settings editor had no effect

Indeed, opening and closing does not help, unless you also open a notebook in the meantime. I can reproduce this reliably.

![repro](https://github.com/deshaw/jupyterlab-execute-time/assets/5832902/d9d83928-e875-4112-a294-99a5174fe603)

The problem here is that the settings UI only adds plugins to UI when the settings are loaded by the extension. ` jupyterlab-execute-time` only loads the settings after opening a notebook.

**Closed** 2024-05-17 15:24 UTC
