### ISSUE TITLE
Execution times not clearing / stacking up

### ISSUE THREAD

**Issue by LloydThinks** [deshaw/jupyterlab-execute-time#38] opened 2021-05-26 12:48 UTC
Hi there!

I've noticed that the execution times are stacking up:

<img width="844" alt="Screenshot - 2021 05 26 - 14 40 05" src="https://user-images.githubusercontent.com/6005999/119661544-b176e980-be30-11eb-9d30-1b4249b9065c.png">

This is likely due to a conflict with the [Collapsible Headings](https://github.com/aquirdTurtle/Collapsible_Headings) extension. When the sections are collapsed, the timings stack up. Although I'm not particularly clear on the exact way in which the timings are stacking up.

When I run a call manually, with the cell open (not collapsed), it clears 2 of the timings and adds 1 more. Currently, the only way I can find to clear them is to manually run each cell many times, clearing 1 timing at a time.

System Information:
- macOS Big Sur version 11.3.1 (20E241)
- Chrome version 90.0.4430.212 (Official Build) (x86_64)
- JupyterLab version 3.0.15
- execute-time version ..?? I don't know how to get this

Let me know if you need any more information.

Lloyd

**Comment by andrewfulton9** [comment] 2021-05-28 18:41
I was able to reproduce this without [Collapsible Headings](https://github.com/aquirdTurtle/Collapsible_Headings) installed, so I don't think that's the cause of the issue.

System Information:
- Ubuntu  18.04.5
- Chrome 90.0.4430.85
- JupyterLab (3.0.15 and 3.0.16)
- jupyterlab-execute-time (v2.0.3 and source build from master branch)

**Comment by ca-scribner** [comment] 2021-05-31 14:06
A colleague just encountered something similar.  She did a simple print, then repeatedly collapsed/expanded the cell and every time a new copy of the same "Last executed..." was added

![image](https://user-images.githubusercontent.com/48125859/120205348-dcc65380-c1f7-11eb-9480-48152bdceec6.png)

**Comment by mlucool** [comment] 2021-06-12 12:34
Fixed in 2.0.4. Thanks for reporting. Closing!

**Closed by mlucool** 2021-06-12 12:34 UTC
