### ISSUE TITLE
Cell output not displayed when execute-time widget enabled

### ISSUE THREAD

**Issue by mbrad092** [deshaw/jupyterlab-execute-time#18] opened 2020-11-18 01:34 UTC
I've installed the widget as described also [here](https://stackoverflow.com/questions/56843745/automatic-cell-execution-timing-in-jupyter-lab) but when I enable it, the output of the cell is no longer displayed.

**Comment by mlucool** [comment] 2020-11-18 14:34
Hi,

Can you provide screenshots (or a gif) and debugging information (browser, lab version)?

**Comment by bhperry** [comment] 2021-01-12 20:08
This is a bug in jupyterlab itself caused by enabling recordTime. It has been fixed here https://github.com/jupyterlab/jupyterlab/pull/8057

**Comment by mlucool** [comment] 2021-01-12 20:37
Thanks @bhperry. Closing this issue.

@mbrad092 please reopen if a jupyterlab upgrade doesn't work.

**Closed by mlucool** 2021-01-12 20:37 UTC
